title: Sean's Python Pyglet Course
description: Learn Python from scratch by making a game with Pyglet
email: sean@seanpackham.com

url: https://seanpackham.com/python-pyglet-course
permalink: pretty

# bump if alterting styles
version: 2

collections:
  lessons:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: lesson

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md